"""
test_DenseDiscMoment.py

Tests for the moment methods of DenseDiscretePhaseType.

The expected values come from reference_values.MOMENT: exact rational
factorial moments converted to raw moments with Stirling numbers and
cross-checked against the probability series generated by
generate_reference_values.py.

The test covers mean, variance, standard deviation, CV, SCV, raw moments and
factorial moments.

Run with:
    python3 -m unittest test_DenseDiscMoment -v

Authors: Juanita Carrascal Mendez, Luciana Bacci Tarazona
Advisor: Juan Fernando Perez Bernal
Version: 1.0
"""

import unittest

import numpy as np

import discrete_fixtures as fx
from DenseDiscPhaseVar import DenseDiscretePhaseType
from matrix_utils import stirling_second, to_dense
from reference_values import MOMENT


def rel_delta(x, rel=1e-10):
    return rel * max(1.0, abs(x))


class DenseDiscMomentTest(unittest.TestCase):
    """Tests for the discrete moment functions."""

    @staticmethod
    def make(vector, matrix):
        return DenseDiscretePhaseType(vector, matrix)

    def setUp(self):
        self.vector, self.matrix = fx.fixture("moment")
        self.var = self.make(self.vector, self.matrix)

    def tearDown(self):
        self.assertLess(np.max(np.abs(to_dense(self.var.A) - self.matrix)), 1.0e-12,
                        "Matrix changed")
        self.assertLess(np.max(np.abs(self.var.alpha - self.vector)), 1.0e-12,
                        "Vector changed")

    def test_expected_value(self):
        self.assertAlmostEqual(self.var.mean(), MOMENT["mean"],
                               delta=rel_delta(MOMENT["mean"]),
                               msg="Expected Value non equal")

    def test_variance(self):
        self.assertAlmostEqual(self.var.var(), MOMENT["var"],
                               delta=rel_delta(MOMENT["var"]),
                               msg="Variance non equal")

    def test_std(self):
        self.assertAlmostEqual(self.var.std(), MOMENT["std"],
                               delta=rel_delta(MOMENT["std"]),
                               msg="Standard Deviation non equal")

    def test_cv(self):
        self.assertAlmostEqual(self.var.cv(), MOMENT["cv"],
                               delta=rel_delta(MOMENT["cv"]),
                               msg="Coefficient of Variation non equal")
        self.assertAlmostEqual(self.var.scv(), MOMENT["scv"],
                               delta=rel_delta(MOMENT["scv"]),
                               msg="Squared Coefficient of Variation non equal")

    def test_moment2(self):
        self.assertAlmostEqual(self.var.moment(2), MOMENT["raw"][2],
                               delta=rel_delta(MOMENT["raw"][2]),
                               msg="Second Moment non equal")

    def test_moment3(self):
        self.assertAlmostEqual(self.var.moment(3), MOMENT["raw"][3],
                               delta=rel_delta(MOMENT["raw"][3]),
                               msg="Third Moment non equal")

    def test_moment4(self):
        self.assertAlmostEqual(self.var.moment(4), MOMENT["raw"][4],
                               delta=rel_delta(MOMENT["raw"][4]),
                               msg="Fourth Moment non equal")

    def test_factorial_moments(self):
        for k in range(1, 5):
            self.assertAlmostEqual(self.var.factorial_moment(k), MOMENT["factorial"][k],
                                   delta=rel_delta(MOMENT["factorial"][k]),
                                   msg=f"Factorial Moment {k} non equal")

    def test_raw_from_factorial_uses_stirling(self):
        fm = [self.var.factorial_moment(j) for j in range(1, 5)]
        expected = sum(stirling_second(4, j) * fm[j - 1] for j in range(1, 5))
        self.assertAlmostEqual(self.var.moment(4), expected, delta=rel_delta(expected))


if __name__ == "__main__":
    unittest.main()
